// <auto-generated />
using System;
using KingWilliamHotelTest.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KingWilliamHotelTest.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KingWilliamHotelTest.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("KingWilliamHotelTest.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount");

                    b.Property<int>("CustomerId");

                    b.Property<DateTime>("EndDate");

                    b.Property<int>("RoomId");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("ReservationId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RoomId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("KingWilliamHotelTest.Models.Room", b =>
                {
                    b.Property<int>("RoomId");

                    b.Property<string>("Category");

                    b.Property<bool>("NeedsCleaning");

                    b.Property<bool>("Unavailable");

                    b.HasKey("RoomId");

                    b.HasIndex("Category");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("KingWilliamHotelTest.Models.RoomDes", b =>
                {
                    b.Property<string>("Category");

                    b.Property<string>("CategoryDesc");

                    b.Property<double>("Rate");

                    b.HasKey("Category");

                    b.ToTable("RoomDess");
                });

            modelBuilder.Entity("KingWilliamHotelTest.Models.Reservation", b =>
                {
                    b.HasOne("KingWilliamHotelTest.Models.Customer")
                        .WithMany("Reservations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KingWilliamHotelTest.Models.Room")
                        .WithMany("Reservations")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KingWilliamHotelTest.Models.Room", b =>
                {
                    b.HasOne("KingWilliamHotelTest.Models.RoomDes", "RoomDes")
                        .WithMany("Rooms")
                        .HasForeignKey("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
